apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  namespace: microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
        - name: log-processor
          image: log-processor:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 9100
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: microservice-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservice-config
                  key: REDIS_PORT
            - name: REDIS_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: microservice-config
                  key: REDIS_CHANNEL
