apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  namespace: microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
        - name: log-processor
          image: log-processor:1.0
          imagePullPolicy: Never
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CHANNEL
              value: "log_channel"
