apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: microservice-app
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080