apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: log-message-processor-policy
  namespace: microservice-app
spec:
  podSelector:
    matchLabels:
      app: log-message-processor
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: redis
      ports:
        - port: 6379
          protocol: TCP
