apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-policy
  namespace: microservice-app
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: todos-api
      ports:
        - port: 6379
          protocol: TCP
    - from:
        - podSelector:
            matchLabels:
              app: log-message-processor
      ports:
        - port: 6379
          protocol: TCP
    - from:
        - podSelector:
            matchLabels:
              app: auth-api
      ports:
        - port: 6379
          protocol: TCP

    - from:
        - podSelector:
            matchLabels:
              app: users-api
      ports:
        - port: 6379
          protocol: TCP

    - from:
        - podSelector:
            matchLabels:
              app: redis-exporter
      ports:
        - port: 6379
          protocol: TCP